oblig2_Yevhen_Verkhalantsev.Web/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using oblig2_Yevhen_Verkhalantsev.Services.AuthServices;
using oblig2_Yevhen_Verkhalantsev.Services.UserServices;
using oblig2_Yevhen_Verkhalantsev.Services.UserServices.Models;

namespace oblig2_Yevhen_Verkhalantsev.Web.Controllers;

public class AuthController: Controller
{
    private readonly IAuthService _authService;
    private readonly IUserService _userService;

    public AuthController(IAuthService authService, 
        IUserService userService)
    {
        _authService = authService;
        _userService = userService;
    }
    
    [HttpGet]
    [Route("LogIn")]
    public async Task<IActionResult> LogIn()
    {
        return View();
    }

    [HttpPost]
    [Route("LogIn")]
    public async Task<IActionResult> LogIn([FromBody] CreateUserHttpPostModel vm)
    {
        var response = await _authService.LogIn(vm.Username, vm.Password);
        if (response.IsError)
        {
            return BadRequest(new {ErrorMessage = response.ErrorMessage});
        }

        return Ok(new {success = true, url = Url.Action("Index", "Home")});
    }
    
    [HttpGet]
    public async Task<IActionResult> SignUp()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> SignUp([FromBody]CreateUserHttpPostModel vm)
    {
        var response = await _userService.Create(vm);
        if (response.IsError)
        {
            return BadRequest(new {ErrorMessage = response.ErrorMessage});
        }
        
        var authResponse = await _authService.LogIn(vm.Username, vm.Password);
        if (authResponse.IsError)
        {
            return BadRequest(new {ErrorMessage = authResponse.ErrorMessage});
        }

        return Ok(new {success = true});

    }
    
    [HttpGet]
    public async Task<IActionResult> LogOut()
    {
        var response = await _authService.LogOut();
        if (response.IsError)
        {
            return RedirectToAction("Index", "Home");
        }

        return RedirectToAction("Index", "Home");
    }
}

oblig2_Yevhen_Verkhalantsev.Web/Controllers/BlogController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using oblig2_Yevhen_Verkhalantsev.Services.BlogServices;
using oblig2_Yevhen_Verkhalantsev.Services.BlogServices.Models;
using oblig2_Yevhen_Verkhalantsev.Web.Models.Blog;

namespace oblig2_Yevhen_Verkhalantsev.Web.Controllers;

public class BlogController: Controller
{
    private readonly IBlogService _blogService;

    public BlogController(IBlogService blogService)
    {
        _blogService = blogService;
    }

    
    [HttpGet]
    [Authorize]
    public async Task<IActionResult> Create()
    {
        return View();
    }
    
    [HttpPost]
    public async Task<IActionResult> Create([FromBody] CreateBlogHttpPostModel vm)
    {
        if (!ModelState.IsValid)
        {
            return BadRequest(ModelState);
        }

        var response = await _blogService.Create(vm);
        if (response.IsError)
        {
            return BadRequest(new
            {
                errorMessage = response.ErrorMessage
            });
        }
        
        return Ok(new
        {
            success = true
        });
    }

    [HttpGet]
    public async Task<IActionResult> BlogList(long id)
    {
        BlogListHttpGetViewModel vm = new BlogListHttpGetViewModel()
        {
            Blogs = await _blogService.GetAllByUserId(id)
        };

        return View(vm);
    }
    
    [HttpGet]
    public async Task<IActionResult> BlogAllList()
    {
        BlogListHttpGetViewModel vm = new BlogListHttpGetViewModel()
        {
            Blogs = await _blogService.GetAll()
        };
        
        return View(vm);
    }

    [HttpGet]
    public async Task<IActionResult> BlogDetails(long id)
    {
         var response = await _blogService.GetById(id);
         if (response.IsError)
         {
             return View(new BlogDetailsHttpGetViewModel()
             {
                 IsError = true,
                 ErrorMessage = response.ErrorMessage
             });
         }
         
         return View(new BlogDetailsHttpGetViewModel()
         {
             IsError = false,
             Blog = response.Value
         });
    }
    
    [HttpGet]
    public async Task<IActionResult> MyBlog(long id)
    {
        return View();
    }
}

oblig2_Yevhen_Verkhalantsev.Web/Controllers/CommentController.cs
using Microsoft.AspNetCore.Mvc;
using oblig2_Yevhen_Verkhalantsev.Services.BlogServices;
using oblig2_Yevhen_Verkhalantsev.Services.CommentServices;
using oblig2_Yevhen_Verkhalantsev.Services.CommentServices.Models;
using oblig2_Yevhen_Verkhalantsev.Services.PostServices;
using oblig2_Yevhen_Verkhalantsev.Web.Models.Comment;

namespace oblig2_Yevhen_Verkhalantsev.Web.Controllers;

public class CommentController: Controller
{
    private readonly IPostService _postService;
    private readonly IBlogService _blogService;
    private readonly ICommentService _commentService;

    public CommentController(IPostService postService, IBlogService blogService, ICommentService commentService)
    {
        _postService = postService;
        _blogService = blogService;
        _commentService = commentService;
    }
    
    [HttpGet]
    public async Task<IActionResult> Create(long id)
    {
        CreateCommentHttpGetViewModel vm = new CreateCommentHttpGetViewModel()
        {
            Blogs = await _blogService.GetAllByUserId(id)
        };
        return View(vm);
    }
    
    [HttpPost]
    public async Task<IActionResult> Create([FromBody] CreateCommentHttpPostModel vm)
    {
        var response = await _commentService.Create(vm);
        if (response.IsError)
        {
            return BadRequest(new
            {
                responseMessage = response.ErrorMessage
            });
        }

        return Ok(new { success = true, result = response.Value});
    }

    [HttpGet]
    public async Task<IActionResult> CommentList()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Delete([FromBody]DeleteCommentHttpPostModel vm)
    {
        var response = await _commentService.Delete(vm);
        if (response.IsError)
        {
            return BadRequest(new
            {
                responseMessage = response.ErrorMessage
            });
        }
        
        return Ok(new { success = true });
    }
    
    [HttpGet]
    public async Task<IActionResult> GetCommentById(long id)
    {
        var response = await _commentService.GetById(id);
        if (response.IsError)
        {
            return BadRequest(new
            {
                responseMessage = response.ErrorMessage
            });
        }
        
        return Ok(new { success = true, result = response.Value});
    }
    
    [HttpPost]
    public async Task<IActionResult> Update([FromBody] UpdateCommentHttpPostModel vm)
    {
        var response = await _commentService.Update(vm);
        if (response.IsError)
        {
            return BadRequest(new
            {
                responseMessage = response.ErrorMessage
            });
        }
        
        return Ok(new { success = true});
    }
    
}

oblig2_Yevhen_Verkhalantsev.Web/Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;
using oblig2_Yevhen_Verkhalantsev.Services.BlogServices;
using oblig2_Yevhen_Verkhalantsev.Services.BlogServices.Models;
using oblig2_Yevhen_Verkhalantsev.Services.PostServices;
using oblig2_Yevhen_Verkhalantsev.Web.Models.Post;

namespace oblig2_Yevhen_Verkhalantsev.Web.Controllers;

public class PostController: Controller
{
    private readonly IPostService _postService;
    private readonly IBlogService _blogService;

    public PostController(IPostService postService, IBlogService blogService )
    {
        _postService = postService;
        _blogService = blogService;
    }
    
    [HttpGet]
    public async Task<IActionResult> Create(long id)
    {
        CreatePostHttpGetViewModel vm = new CreatePostHttpGetViewModel()
        {
            Blogs = await _blogService.GetAllByUserId(id)
        };
        
        return View(vm);
    }

    [HttpPost]
    public async Task<IActionResult> Create([FromBody] CreatePostHttpPostModel vm)
    {
        var response = await _postService.Create(vm);
        if (response.IsError)
        {
            return BadRequest(new
            {
                responseMessage = response.ErrorMessage
            });
        }

        return Ok(new { success = true });
    }

    [HttpGet]
    public async Task<IActionResult> PostList(long id)
    {
        PostListHttpGetViewModel vm = new PostListHttpGetViewModel()
        {
            Posts = _postService.GetAllByUserId(id)
        };
        return View(vm);
    }

    [HttpGet]
    public async Task<IActionResult> Update(long id)
    {
        var response = await _postService.GetById(id);
        if(response.IsError)
        {
            return View(new UpdatePostHttpGetViewModel()
            {
                Blogs = await _blogService.GetAll(),
                ErrorMessage = response.ErrorMessage,
                IsError = true
            });
        }

        return View(new UpdatePostHttpGetViewModel()
        {
            Blogs = await _blogService.GetAll(),
            IsError = false,
            Post = response.Value
        });

    }
    
    [HttpPost]
    public async Task<IActionResult> Update([FromBody] UpdatePostHttpPostModel vm)
    {
        var response = await _postService.Update(vm);
        if (response.IsError)
        {
            return BadRequest(new
            {
                responseMessage = response.ErrorMessage
            });
        }

        return Ok(new
        {
            success = true
        });
    }

    [HttpPost]
    public async Task<IActionResult> Delete([FromBody] DeletePostHttpPostModel vm)
    {
        var response = await _postService.Delete(vm);
        if (response.IsError)
        {
            return BadRequest(new
            {
                responseMessage = response.ErrorMessage
            });
        }

        return Ok(new
        {
            success = true
        });
    }
    
    
    [HttpPost]
    public async Task<IActionResult> GetById([FromBody] GetByIdPostHttpPostModel vm)
    {
        var response = await _postService.GetById(vm.Id);
        if (response.IsError)
        {
            return BadRequest(new
            {
                responseMessage = response.ErrorMessage
            });
        }

        return Ok(new
        {
            success = true,
            result = response.Value
        });
    }
    
    [HttpGet]
    public async Task<IActionResult> GetPostsByBlog(long id)
    {
        var response = await _postService.GetPostsByBlog(id);
        if (response.IsError)
        {
            return Ok(new
            {
                success = false,
                result = Enumerable.Empty<CreatePostHttpPostModel>(),
                responseMessage = response.ErrorMessage
            });
        }

        return Ok(new
        {
            success = true,
            result = response.Value
        });
    }

}

oblig2_Yevhen_Verkhalantsev.Web/Views/Shared/_Layout.cshtml
@using oblig2_Yevhen_Verkhalantsev.Services.UserServices
@inject ICurrentUserContext CurrentUserContext

<!DOCTYPE html>
<html lang="en">

<head>
    
    <meta charset="utf-8">
    <title>Oblig2 DTE-2802</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="~/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Roboto:wght@500;700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet"/>

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/css/style.css" rel="stylesheet">
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Blog
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            
            <li><a class="dropdown-item" href="@Url.Action("BlogAllList", "Blog")">All blogs</a></li>
            
            @if (CurrentUserContext.IsAuthenticated)
            {
              <li><a class="dropdown-item" href="@Url.Action("Create", "Blog", new { @id = CurrentUserContext.Id })">Create blog</a></li>
              <li><a class="dropdown-item" href="@Url.Action("BlogList", "Blog", new { @id = CurrentUserContext.Id })">My Blog List</a></li>
            }
            else
            {
              <li class="dropdown-item">Please login to create a blog.</li>
              <li class="dropdown-item">Please login to see the blog list.</li>
            }

          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Post
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            
            @if (CurrentUserContext.IsAuthenticated)
            {
              <li><a class="dropdown-item" href="@Url.Action("Create", "Post", new { @id = CurrentUserContext.Id })">Create Post</a></li>
              <li><a class="dropdown-item" href="@Url.Action("PostList", "Post", new { @id = CurrentUserContext.Id })">My Post List</a></li>
            }
            else
            {
              <li class="dropdown-item">Please login to create a post.</li>
              <li class="dropdown-item">Please login to see the post list.</li>
            }
            
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Comment
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            
            @if (CurrentUserContext.IsAuthenticated)
            {
              <li><a class="dropdown-item" href="@Url.Action("Create", "Comment", new { @id = CurrentUserContext.Id })">Create comment</a></li>
              <li><a class="dropdown-item" href="@Url.Action("CommentList", "Comment", new { @id = CurrentUserContext.Id })">My Comment List</a></li>
            }
            else
            {
              <li class="dropdown-item">Please login to create a comment.</li>
              <li class="dropdown-item">Please login to see the comment list.</li>
            }
          </ul>
        </li>

      </ul>
    </div>
  </div>
  <div class="nav-item dropdown">
    @if (CurrentUserContext.IsAuthenticated)
    {
      <!-- Display this icon when the user is authenticated -->
      <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
        <img class="rounded-circle me-lg-2" src="~/img/user.jpg" alt="" style="width: 40px; height: 40px;">
        <span class="d-none d-lg-inline-flex">@CurrentUserContext.Username</span>
      </a>
      <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
        <a href="@Url.Action("LogOut", "Auth")" class="dropdown-item" onclick="return confirm('Are you sure you want to log out?');">Log Out</a>
      </div>
    }
    else
    {
      <!-- Display this icon when the user is not authenticated -->
      <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
        <img class="rounded-circle me-lg-2" src="~/img/ic_login.png" alt="" style="width: 40px; height: 40px;">
        <span class="d-none d-lg-inline-flex">Guest</span>
      </a>
      <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
        <a href="@Url.Action("LogIn", "Auth")" class="dropdown-item">Log In</a>
        <a href="@Url.Action("SignUp", "Auth")" class="dropdown-item">Sign Up</a>
      </div>
    }
   
  </div>
</nav>

<div class="container-fluid position-relative p-0">


    @RenderBody()
    
</div>

<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/lib/chart/chart.min.js"></script>
<script src="~/lib/easing/easing.min.js"></script>
<script src="~/lib/waypoints/waypoints.min.js"></script>
<script src="~/lib/owlcarousel/owl.carousel.min.js"></script>
<script src="~/lib/tempusdominus/js/moment.min.js"></script>
<script src="~/lib/tempusdominus/js/moment-timezone.min.js"></script>
<script src="~/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

<!-- Template Javascript -->
@* <script src="~/js/main.js"></script> *@

@await RenderSectionAsync("Scripts", required: false)

</body>

</html>